<a href="https://colab.research.google.com/github/WHOGONCHECKME/GitHubTest/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

In [27]:
a = np.full((5,5),1)
b = np.full((3,3),0)
c = np.full((1,1),9)
print(a)
print(b)
print(c)
b[1,1] = 9
print(b)
a[1:4,1:4] = b
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[9]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[9]]


In [18]:
d = np.append(c,[1], size = (3,3))
print(d)

TypeError: ignored

In [20]:
d = np.array([[1,1,1,1,1],[1,0,0,0,1],[1,0,9,0,1],[1,0,0,0,1],[1,1,1,1,1,]])
print(d)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [28]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [32]:
a += 2

In [33]:
a

array([5, 6, 7, 8])

In [34]:
a=1

In [37]:
range(25)

range(0, 25)

In [35]:
mat = np.full([5,5],a+=1)

SyntaxError: ignored

In [64]:
#Create a matrix of 6x5 increasing integer
a = np.full([6,5],0)
val = 0
for i in range(6):
  for j in range(5):
    val += 1
    a[i,j] = val
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [81]:
#calling on values 11, 12, 16, 17
a[2:4,0:2]


array([[11, 12],
       [16, 17]])

In [74]:
y = np.arange(30).reshape(6,5)
y + 1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [86]:
a[0:4:1,1:5:1]
a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [120]:
c = np.array(a[[0,0],[3,4]])
d = np.array(a[4:6,3:5])
#b = np.vstack(c, d)
print(c)
print(d)
b = np.vstack([c, d])
b

[4 5]
[[24 25]
 [29 30]]


array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [122]:
a[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])